http:
  routers:
    emilzackrisson-se:
      entryPoints:
        - websecure-external
      rule: Host(`emilzackrisson.se`)
      middlewares:
        - emilzackrisson-se-redirect
      service: home
    authentik:
      entryPoints:
        - websecure-external
      rule: Host(`auth.emilzackrisson.se`)
      service: authentik-kubernetes
    code-server-unraid:
      entryPoints:
        - websecure-internal
      rule: Host(`code.unraid.local.emilzackrisson.se`)
      middlewares:
        - authentik
        - admin-ipwhitelist
      service: code-server-unraid
      tls:
        certResolver: letsencrypt
    technitium:
      entryPoints:
        - websecure-internal
      rule: Host(`technitium.local.emilzackrisson.se`)
      middlewares:
        - authentik
        - admin-ipwhitelist
      service: technitium
    filebrowser:
      entryPoints:
        - websecure-internal
      rule: Host(`filebrowser.local.emilzackrisson.se`)
      middlewares:
        - authentik
        - admin-ipwhitelist
      service: filebrowser
    home-assistant:
      entryPoints:
        - websecure-internal
        - websecure-external
      rule: Host(`ha.local.emilzackrisson.se`) || Host(`ha.emilzackrisson.se`)
      service: home-assistant
    nextcloud-int:
      entryPoints:
        - websecure-internal
      rule: Host(`nextcloud.local.emilzackrisson.se`)
      middlewares:
        - nextcloud-redirect
        - nextcloud-middlewares-secure-headers
      service: nextcloud
    nextcloud-ext:
      entryPoints:
        - websecure-external
      rule: Host(`nextcloud.emilzackrisson.se`)
      middlewares:
        - nextcloud-redirect
        - nextcloud-middlewares-secure-headers
      service: nextcloud
    qbittorrent:
      entryPoints:
        - websecure-internal
      rule: Host(`tor.local.emilzackrisson.se`)
      middlewares:
        - authentik
        - admin-ipwhitelist
      service: qbittorrent
    prx:
      entryPoints:
        - websecure-internal
      rule: Host(`prx.local.emilzackrisson.se`)
      middlewares:
        - admin-ipwhitelist
      service: prx
    portainer:
      entryPoints:
        - websecure-internal
      rule: Host(`portainer.local.emilzackrisson.se`)
      middlewares:
        - portainer-redirect
        - admin-ipwhitelist
      service: portainer
    prowlarr:
      entryPoints:
        - websecure-internal
      rule: Host(`prowlarr.local.emilzackrisson.se`)
      middlewares:
        - authentik
      service: prowlarr
    immich:
      entryPoints:
        - websecure-internal
      rule: Host(`immich.local.emilzackrisson.se`)
      middlewares:
        - maintenance
      service: immich
    filer:
      entryPoints:
        - websecure-external
      rule: Host(`filer.emilzackrisson.se`)
      middlewares:
        - authentik
      service: dufs
    filer-local:
      entryPoints:
        - websecure-internal
      rule: Host(`filer.local.emilzackrisson.se`)
      middlewares:
        - authentik
      service: dufs
    home:
      entryPoints:
        - websecure-external
      rule: Host(`home.emilzackrisson.se`)
      middlewares:
        - authentik
      service: home
    radarr:
      entryPoints:
        - websecure-external
      rule: Host(`radarr.emilzackrisson.se`)
      middlewares:
        - authentik
        - radarr-theme
      service: radarr
    sonarr:
      entryPoints:
        - websecure-external
      rule: Host(`sonarr.emilzackrisson.se`)
      middlewares:
        - authentik
        - sonarr-theme
      service: sonarr
    traefik:
      entryPoints:
        - websecure-internal
      rule: Host(`traefik.local.emilzackrisson.se`)
      middlewares:
        - authentik
        - admin-ipwhitelist
      service: api@internal
    bazarr:
      entryPoints:
        - websecure-external
      rule: Host(`bazarr.emilzackrisson.se`)
      middlewares:
        - authentik
      service: bazarr
    whoami:
      entryPoints:
        - websecure-internal
      rule: Host(`whoami.local.emilzackrisson.se`)
      middlewares:
        - admin-ipwhitelist
      service: whoami
    whoami-external:
      entryPoints:
        - websecure-external
      rule: Host(`whoami.emilzackrisson.se`)
      middlewares:
        - authentik
      service: whoami
    calibre-web:
      entryPoints:
        - websecure-external
      rule: Host(`books.emilzackrisson.se`)
      middlewares:
        - authentik
      service: calibre-web
    penpot:
      entryPoints:
        - websecure-internal
      rule: Host(`penpot.local.emilzackrisson.se`)
      service: penpot
    infisical:
      entryPoints:
        - websecure-internal
      rule: Host(`infisical.local.emilzackrisson.se`)
      service: infisical
    cockpit-docker:
      entryPoints:
        - websecure-internal
      rule: Host(`cockpit.docker-prod.local.emilzackrisson.se`)
      middlewares:
        - admin-ipwhitelist
      service: cockpit-docker
      tls:
        certResolver: letsencrypt
    lyckebyansfvo:
      entryPoints:
        - websecure-external
      rule: Host(`lyckebyansfvo.emilzackrisson.se`)
      service: lyckebyansfvo
    powerdns-admin:
      entryPoints:
        - websecure-internal
      rule: Host(`pdns.local.emilzackrisson.se`)
      middlewares:
        - admin-ipwhitelist
      service: powerdns-admin
    test:
      entryPoints:
        - string
      rule: string
      middlewares:
        - string
      service: testService
      tls:
        certResolver: string
  services:
    authentik-kubernetes:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://10.10.0.58:9443
    code-server-unraid:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.20:8443
    technitium:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.3:5380
    filebrowser:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.20:8080
    home-assistant:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.21:8119
    nextcloud:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://10.10.0.99:8443
    qbittorrent:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:8082
    prx:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://10.10.0.19:8006
    portainer:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://portainer.ingress.kube.local.emilzackrisson.se
    cockpit-docker-01-prod:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.132:9090
    prowlarr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:9696
    immich:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.20:2283
    kasm:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.20:6333
    dufs:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:5000
    home:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://homepage.ingress.kube.local.emilzackrisson.se
    radarr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:7878
    sonarr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:8989
    bazarr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:6767
    whoami:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.8:8054
    calibre-web:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.20:8087
    penpot:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:9002
    infisical:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:8085
    cockpit-docker:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://10.10.0.99:9090
    lyckebyansfvo:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://lyckebyansfvo.ingress.kube.local.emilzackrisson.se
    powerdns-admin:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://10.10.0.99:5380
    testService:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: 1.1.1.1
tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13
